modLoader="javafml"
loaderVersion="${loader_version_range}"

license="${mod_license}"
issueTrackerURL="https://github.com/Ovear-Mitama/Anima/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://modrinth.com/mod/anima"
logoFile="anima.png"

description='''
A client-side animation library for text and textures, including real 3D world text and particles.
'''

[[mixins]]
config="anima.client.mixins.json"
clientOnly=true

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
